# Generated by Django 4.2.1 on 2023-06-09 00:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0002_remove_category_is_fav_recipes_is_fav"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipes",
            name="recipes_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="recipes"
            ),
        ),
    ]
